#!/bin/zsh

file="$1"
start="$2"
end="$3"

if [[ -z "$file" || ! -f "$file" ]]; then
  echo "usage: $(basename $0) <file> [start_seconds] [end_seconds]"
  exit 1
fi
file=$(realpath "$file")

opts=()
if [[ -n "$start" && "$start" -gt 0 ]]; then
  opts+=(-ss "$start")
fi
if [[ -n "$end" && "$end" -gt 0 ]]; then
  opts+=(-to "$end")
fi
opts+=(-hide_banner -c copy)

output="${file:r}.new.${file:e}"

if [[ -e "$output" ]]; then
  local n=1
  while [[ -e "${file:r}.new${n}.${file:e}" ]]; do (( n++ )); done;
  output="${file:r}.new${n}.${file:e}"
fi

echo "Converting: $file -> $output"
ffmpeg -i "$file" "${opts[@]}" "$output"

echo "Done"
