#!/bin/zsh

IPOD="/run/media/$USER/LISDEN"
MUSIC="$HOME/Music/ipod/"
PLAYLISTS="$HOME/Music/Playlists/ipod/"

if [[ ! -d "$IPOD" ]]; then
    echo "iPod not found. Be sure to mount the device and try again."
    exit 1
fi

echo "Syncing music files to iPod..."
rsync -rtvPh --modify-window=1 --size-only --delete "$MUSIC" "$IPOD/music/"

echo "Syncing playlist files..."
rsync -rtvPh --modify-window=1 --size-only --delete "$PLAYLISTS" "$IPOD/Playlists/"

sync
echo "Sync complete."

echo "The iPod can be safely ejected now."