#!/bin/zsh

P_DIR="$HOME/Music/Playlists"
P_DIR_IPOD="$P_DIR/ipod"
P_DIR_ITUNES="$P_DIR/itunes"

for p in $P_DIR/*(.); do
  print "Processing '$(basename "$p")'"
  sed '/^#/d; s|^/music/master-lib|/music|; s|\.flac$|.m4a|' "$p" > "$P_DIR_IPOD/$(basename "$p")"
  sed '/^#/d; s|^/music/master-lib|Y:\\ipod|; s|/|\\|g; s|\.flac$|.m4a|' "$p" > "$P_DIR_ITUNES/$(basename "$p")"
done

print "[DONE]"
