#!/bin/zsh

MODES=( "ipod" "itunes" )
MODE_FROM=""
MODE_TO=""

show_help(){
  cat <<EOF
Usage:
  $(basename $0) <from> <to> <file>

Options:
  from      The type of playlist to convert from
  to        The type of playlist to convert to
  file      Path to a playlist file or a directory containing playlist files

Valid types are:  itunes, ipod
EOF
}

process_playlist() {
  f="$1"
  case "$2" in
    ipod)
      if ! grep -m 1 -Fq 'Y:\ipodLibrary' "$f"; then
        echo "Skipping file '$f' (not an iTunes playlist)"
        return
      fi
      sed -i '/^#/d' "$f"
      sed -i 's|\\|/|g' "$f"
      sed -i 's|Y:/ipodLibrary|/<HDD0>/music|g' "$f"
      mv "$f" "${f:r}.m3u8"
      ;;
    itunes)
      if ! grep -m 1 -Fq '/<HDD0>' "$f"; then
        echo "Skipping file '$f' (not an iPod playlist)"
        return
      fi
      sed -i 's#^/<HDD0>##' "$f"
      sed -i 's|/music|Y:\\ipodLibrary|g' "$f"
      sed -i 's|/|\\|g' "$f"
      mv "$f" "${f:r}.m3u"
      ;;
  esac
}

if [ "$#" -lt 3 ]; then
  show_help
  exit 1
fi

MODE_FROM="$1"
MODE_TO="$2"
TARGET_PATH="$3"

if [[ ! " ${MODES[*]} " =~ " ${MODE_FROM} " ]]; then
  echo "Error: Invalid type '$MODE_FROM'." >&2
  exit 1
fi
if [[ ! " ${MODES[*]} " =~ " ${MODE_TO} " ]]; then
  echo "Error: Invalid type '$MODE_TO'." >&2
  exit 1
fi
if [ ! -e "$TARGET_PATH" ]; then
  echo "Error: File or directory not found" >&2
  exit 1
fi

if [ -d "$TARGET_PATH" ]; then
  echo "Processing directory: $TARGET_PATH"
  for file in "$TARGET_PATH"/*; do
    process_playlist "$file" "$MODE_TO"
  done
elif [ -f "$TARGET_PATH" ]; then
  echo "Processing file: $TARGET_PATH"
  process_playlist "$TARGET_PATH" "$MODE_TO"
else
  echo "Error: Invalid file '$TARGET_PATH'." >&2
  exit 1
fi

echo "Done!"
