#!/bin/zsh

dir="$1"

if [ -z "$dir" ]; then
  echo "Usage: $(basename $0) <directory>" >&2
  exit 1
fi

if [ ! -d "$dir" ]; then
  echo "Error: directory must exist" >&2
  exit 1
fi

dir=$(realpath "$dir")

find "$dir" -iname "*.m3u" -type f | while IFS= read -r file; do
  sed -i '/^#/d' "$file"
  sed -i 's|\\|/|g' "$file"
  sed -i 's|Y:/ipodLibrary|/music|g' "$file"
  mv "$file" "${file%.*}.m3u8"
done

echo "Done!"
